import react , {useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Image2 from 'next/future/image'
import { Popover } from 'react-tiny-popover'

export default function Home() {
  let open = react.createRef()
  let close = react.createRef()
  const [isPopoverOpen, setIsPopoverOpen] = useState(false);
  const opening = () => {
    open.current.classList.add('hidden')
    close.current.classList.remove('hidden')
  }
  const closeing = () => {
    open.current.classList.remove('hidden')
    close.current.classList.add('hidden')
  }
  const enter = () => {
    setIsPopoverOpen(true)
  }
  const leave = () => {
    setIsPopoverOpen(false)
  }
  return (<>
    <Head>
      <title>Article preview component - ProjectsByDailyreadingAdmin</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <section className='bg min-h-[100vh] flex flex-col md:flex-row justify-center items-center '>
        <Image2 className='rounded-t-lg md:rounded-t-none md:rounded-l-lg w-[80%] md:w-64 h-auto md:h-60' src="/images/drawers.jpg" width={300} height={300} />
        <div className='pt-6 bg-white w-[80%] md:w-[27rem] h-auto md:h-60 rounded-b-lg md:rounded-b-none md:rounded-r-lg shadow-xl'>
          <h3 className='px-6 p-1 font font-bold text-md text-gray-500'>Shift the overall look and feel by adding these wonderful touches to furniture in your home</h3>
          <p className='px-6 p-1 mb-2 font font-medium text-sm text-gray-400'>Ever been in a room and felt like something was missing? Perhaps it felt slightly bare and uninviting. I&apos;ve got some simple tips to help you make any room feel complete.</p>
          <div ref={open} className='flex px-6 pb-6 md:flex'>
            <Image className='rounded-full' src="/images/avatar-michelle.jpg" width={50} height={50} alt="article"/>
            <div className='flex flex-col ml-4 mt-2'>
              <div className='font-bold text-sm text-gray-700 items-center font'>Michelle Appleton</div>
              <div className='font-bold text-sm text-gray-400 items-center font'>28 Jun 2020</div>
            </div>
            <Popover
              isOpen={isPopoverOpen}
              positions={['top']}
              content={<div onMouseEnter={enter} className='hidden md:flex bg-gray-700 p-4 rounded-lg items-center'>
              <span className='font font-medium text-xs text-gray-400 tracking-[0.4em]'>SHARE</span>
              <Image2 className='h-4 w-4 ml-4 mx-2 cursor-pointer' src="/images/icon-facebook.svg" width={40} height={40} />
              <Image2 className='h-4 w-4 mx-2 cursor-pointer' src="/images/icon-twitter.svg" width={40} height={40} />
              <Image2 className='h-4 w-4 mx-2 cursor-pointer' src="/images/icon-pinterest.svg" width={40} height={40} /><div className="popover-arrow__arrow popover-arrow__arrow--bc"></div></div>}
            >
            <div onClick={opening} onMouseEnter={enter} onMouseLeave={leave} className='bg-gray-200 p-3 rounded-full ml-auto my-auto'>
              <Image2 className='h-4 w-5' src="/images/icon-share.svg" width={10} height={10} />
            </div>
            </Popover>
          </div>
          <div ref={close} className="hidden md:hidden">
            <div className='flex bg-gray-700 p-6 rounded-b-lg items-center'>
              <span className='font font-medium text-sm text-gray-400 tracking-[0.4em]'>SHARE</span>
              <Image2 className='h-7 w-7 ml-4 mx-2' src="/images/icon-facebook.svg" width={40} height={40} />
              <Image2 className='h-7 w-7 mx-2' src="/images/icon-twitter.svg" width={40} height={40} />
              <Image2 className='h-7 w-7 mx-2' src="/images/icon-pinterest.svg" width={40} height={40} />
              <div onClick={closeing} className='bg-gray-400 p-3 rounded-full ml-auto my-auto'>
                <Image2 className='h-4 w-5' src="/images/icon-share2.svg" width={10} height={10} />
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  </>
  )
}
