import react from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Image2 from 'next/future/image'

export default function Home() {
  let close1 = react.createRef()
  let bold1 = react.createRef()
  const open1 = () => {
    close1.current.classList.toggle('hidden')
    bold1.current.classList.toggle('fontBold')
  }
  let close2 = react.createRef()
  let bold2 = react.createRef()
  const open2 = () => {
    close2.current.classList.toggle('hidden')
    bold2.current.classList.toggle('fontBold')
  }
  let close3 = react.createRef()
  let bold3 = react.createRef()
  const open3 = () => {
    close3.current.classList.toggle('hidden')
    bold3.current.classList.toggle('fontBold')
  }
  let close4 = react.createRef()
  let bold4 = react.createRef()
  const open4 = () => {
    close4.current.classList.toggle('hidden')
    bold4.current.classList.toggle('fontBold')
  }
  let close5 = react.createRef()
  let bold5 = react.createRef()
  const open5 = () => {
    close5.current.classList.toggle('hidden')
    bold5.current.classList.toggle('fontBold')
  }
  return (<>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='md:mx-24'>
        {/* <Image src="/images/bg-pattern-desktop.svg" alt="" layout="fill" className='hidden md:block -z-10' />
        <Image src="/images/bg-pattern-mobile.svg" alt="" layout="fill" className='md:hidden -z-10' /> */}
        <section className='bg-white mx-8 my-8 flex flex-col md:flex-row justify-center md:justify-end items-center font mt-28 rounded-xl '>
            <Image2 src="/images/illustration-woman-online-mobile.svg" className='md:hidden absolute top-0' width={240} height={240} alt="" />
            <Image2 src="/images/illustration-woman-online-desktop.svg" className='hidden md:inline lg:hidden absolute left-0' width={330} height={330} alt="" />
            <Image2 src="/images/illustration-woman-online-desktop.svg" className='hidden lg:inline absolute left-0' width={440} height={440} alt="" />
          <div className='w-full pt-32 md:w-[40%] md:mx-32 md:mb-16'>
              <h1 className='text-4xl text-black text-center md:text-left md:ml-4 mt-8 my-4 font-bold'>FAQ</h1>
              <div>
                <div onClick={open1} className='flex justify-between my-2'>
                  <h3 ref={bold1} className='text-gray-500 font-normal ml-5 text-sm hover:text-[#F47C57]'>How many team members can I invite?</h3>
                  <svg className='mt-2 mr-4' width="10" height="7" xmlns="http://www.w3.org/2000/svg"><path d="M1 .799l4 4 4-4" stroke="#F47B56" stroke-width="2" fill="none" fill-rule="evenodd"/></svg>
                </div>
                <p ref={close1} className='text-gray-500 font-normal ml-5 mr-2 text-sm hidden'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque dolores iusto accusantium.</p>
                <div className='border-b-[0.5px] border-gray-400 h-2 mx-4 mb-4'></div>
              </div>
              <div>
                <div onClick={open2} className='flex justify-between my-2'>
                  <h3 ref={bold2} className='text-gray-500 font-normal ml-5 mr-2 text-sm hover:text-[#F47C57]'>What is the maximum file upload size?</h3>
                  <svg className='mt-2 mr-4' width="10" height="7" xmlns="http://www.w3.org/2000/svg"><path d="M1 .799l4 4 4-4" stroke="#F47B56" stroke-width="2" fill="none" fill-rule="evenodd"/></svg>
                </div>
                <p ref={close2} className='text-gray-500 font-normal ml-5 mr-2 text-sm hidden'>No more than 2GB. All files in your account must fit your allotted storage space.</p>
                <div className='border-b-[0.5px] border-gray-400 h-2 mx-4 mb-4'></div>
              </div>
              <div>
                <div onClick={open3} className='flex justify-between my-2'>
                  <h3 ref={bold3} className='text-gray-500 font-normal ml-5 mr-2 text-sm hover:text-[#F47C57]'>How do I reset my password?</h3>
                  <svg className='mt-2 mr-4' width="10" height="7" xmlns="http://www.w3.org/2000/svg"><path d="M1 .799l4 4 4-4" stroke="#F47B56" stroke-width="2" fill="none" fill-rule="evenodd"/></svg>
                </div>
                <p ref={close3} className='text-gray-500 font-normal ml-5 mr-2 text-sm hidden'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque dolores iusto accusantium.</p>
                <div className='border-b-[0.5px] border-gray-400 h-2 mx-4 mb-4'></div>
              </div>
              <div>
                <div onClick={open4} className='flex justify-between my-2'>
                  <h3 ref={bold4} className='text-gray-500 font-normal ml-5 mr-2 text-sm hover:text-[#F47C57]'>Can I cancel my subscription?</h3>
                  <svg className='mt-2 mr-4 ' width="10" height="7" xmlns="http://www.w3.org/2000/svg"><path d="M1 .799l4 4 4-4" stroke="#F47B56" stroke-width="2" fill="none" fill-rule="evenodd"/></svg>
                </div>
                <p ref={close4} className='text-gray-500 font-normal ml-5 mr-2 text-sm hidden'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque dolores iusto accusantium.</p>
                <div className='border-b-[0.5px] border-gray-400 h-2 mx-4 mb-4'></div>
              </div>
              <div>
                <div onClick={open5} className='flex justify-between my-2'>
                  <h3 ref={bold5} className='text-gray-500 font-normal ml-5 mr-2 text-sm hover:text-[#F47C57]'>Do you provide additional support?</h3>
                  <svg className='mt-2 mr-4' width="10" height="7" xmlns="http://www.w3.org/2000/svg"><path d="M1 .799l4 4 4-4" stroke="#F47B56" stroke-width="2" fill="none" fill-rule="evenodd"/></svg>
                </div>
                <p ref={close5} className='text-gray-500 font-normal ml-5 mr-2 text-sm hidden'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque dolores iusto accusantium.</p>
                <div className='border-b-[0.5px] border-gray-400 h-2 mx-4 mb-4'></div>
              </div>
          </div>
        </section>
      </main>
      </>
  )
}
